# tasks file for deploy role
---
- name: Creates backend app directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/backend-app # Use absolute path for clarity
    state: directory
    owner: ubuntu # Ensure ubuntu owns it
    group: ubuntu # Ensure ubuntu group
    mode: '0755'
  become: true # May need to be root to create dir in /home/ubuntu if initial user isn't ubuntu

- name: Unarchive backend files into ubuntu user's backend-app directory
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-app # Use absolute path
    remote_src: no
    # Ensure permissions allow ubuntu user to read/write after unarchiving
    # by default, unarchive preserves permissions from tar. If those are root, ubuntu can't use them.
    # common_opts: --no-same-owner --no-same-permissions (if needed, check your artifact)
    # Alternatively, chown task afterwards:
  become: true # To write to /home/ubuntu/backend-app

- name: Ensure correct ownership of unarchived backend files
  ansible.builtin.file:
    path: /home/ubuntu/backend-app
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
  become: true # Root needed to change ownership

# --- Block to Install Node.js and npm using NVM (Node Version Manager) ---
- name: Ensure prerequisites for NVM and building Node.js (curl, build-essential)
  ansible.builtin.apt:
    name:
      - curl
      - build-essential
    state: present
    update_cache: yes
  become: true

- name: Check if NVM is already installed for user 'ubuntu'
  ansible.builtin.stat:
    path: /home/ubuntu/.nvm/nvm.sh
  become: true
  become_user: ubuntu
  register: nvm_check

- name: Download and install NVM for user 'ubuntu'
  ansible.builtin.shell: |
    export NVM_DIR="/home/ubuntu/.nvm"
    mkdir -p "$NVM_DIR"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
  when: not nvm_check.stat.exists
  register: nvm_install_result
  changed_when: nvm_install_result.stdout is defined and 'already installed' not in nvm_install_result.stdout

- name: Ensure NVM sourcing lines are in .bashrc for user 'ubuntu'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^export NVM_DIR="\$HOME\/\.nvm"$'
    line: 'export NVM_DIR="$HOME/.nvm"'
    state: present
    create: yes
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true # Become root to manage file owned by another user

- name: Add NVM script sourcing to .bashrc for user 'ubuntu'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^\s*\[ -s "\$NVM_DIR\/nvm\.sh" \] && \\\. "\$NVM_DIR\/nvm\.sh"\s*# This loads nvm\s*$'
    line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
    state: present
  become: true # Become root

- name: Add NVM bash completion sourcing to .bashrc for user 'ubuntu'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^\s*\[ -s "\$NVM_DIR\/bash_completion" \] && \\\. "\$NVM_DIR\/bash_completion"\s*# This loads nvm bash_completion\s*$'
    line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion'
    state: present
  become: true # Become root

# RESTORING THIS TASK CAREFULLY - Stage 1: NVM and Node install
- name: Install latest LTS Node.js and set as default using NVM for user 'ubuntu'
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"
    # Source NVM
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    # Install the latest LTS version
    nvm install --lts
    # Set the installed LTS as the default
    nvm alias default lts/*
    # Ensure it's used in current shell
    nvm use default
    echo "NVM setup complete. Node version: $(node -v), NPM version: $(npm -v)"
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
    NVM_DIR: /home/ubuntu/.nvm
  register: nvm_node_install # Restore register
  changed_when: "'Now using node' in nvm_node_install.stdout or 'Checksums matched' in nvm_node_install.stdout" # Restore simplified changed_when

- name: Show Node and NPM versions installed via NVM # Restore debug task
  ansible.builtin.debug:
    msg: "{{ nvm_node_install.stdout_lines }}"
# --- End of Node.js Installation Block using NVM ---

- name: Installing Node Dependencies
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"
    # Source NVM to make node and npm available
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install
  args:
    executable: /bin/bash
    chdir: /home/ubuntu/backend-app # Use absolute path
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
    NVM_DIR: /home/ubuntu/.nvm

- name: Installing PM2 globally using NVM's Node
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"
    # Source NVM
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install pm2 -g
  args:
    executable: /bin/bash
  become: true
  become_user: ubuntu
  environment:
    HOME: /home/ubuntu
    NVM_DIR: /home/ubuntu/.nvm
  register: pm2_global_install
  changed_when: pm2_global_install.stdout is defined and ("added " in pm2_global_install.stdout or "changed " in pm2_global_install.stdout)

- name: Ensuring app is started/restarted with PM2
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"
    # Source NVM
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    pm2 startOrRestart ecosystem.config.js
  become: true
  become_user: ubuntu
  args:
    chdir: /home/ubuntu/backend-app # Use absolute path
    executable: /bin/bash
  environment:
    HOME: /home/ubuntu
    PM2_HOME: /home/ubuntu/.pm2
    NVM_DIR: /home/ubuntu/.nvm
  register: execute_node

- name: Print PM2 start/restart message
  ansible.builtin.debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: Configure pm2 to start as service on system boot
  become: true # Run as root
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"

    NODE_PATH_CMD="export NVM_DIR='/home/ubuntu/.nvm'; [ -s '$NVM_DIR/nvm.sh' ] && . '$NVM_DIR/nvm.sh'; which node"
    PM2_PATH_CMD="export NVM_DIR='/home/ubuntu/.nvm'; [ -s '$NVM_DIR/nvm.sh' ] && . '$NVM_DIR/nvm.sh'; which pm2"

    NODE_PATH_UNDER_NVM=$(su - ubuntu -c "$NODE_PATH_CMD")
    PM2_PATH_UNDER_NVM=$(su - ubuntu -c "$PM2_PATH_CMD")

    if [ -z "$PM2_PATH_UNDER_NVM" ] || [ -z "$NODE_PATH_UNDER_NVM" ]; then
      echo "Critical: Could not find pm2 or node under NVM for user ubuntu. Cannot setup startup script."
      exit 1 # This is important for a real run
    fi
    
    echo "Debug: Node path for PM2 startup: $NODE_PATH_UNDER_NVM"
    echo "Debug: PM2 path for PM2 startup: $PM2_PATH_UNDER_NVM"

    env PATH="$PATH:$(dirname "$PM2_PATH_UNDER_NVM"):$(dirname "$NODE_PATH_UNDER_NVM")" "$PM2_PATH_UNDER_NVM" startup systemd -u ubuntu --hp /home/ubuntu
  args:
    executable: /bin/bash
  register: pm2_startup
  changed_when: >
    pm2_startup.stdout is defined and
    'already setup' not in pm2_startup.stdout and
    ('systemd detected' in pm2_startup.stdout or
     '+ Done' in pm2_startup.stdout or
     'command successfully executed' in pm2_startup.stdout or
     'successfully set up' in pm2_startup.stdout or
     'command has been successfully executed' in pm2_startup.stdout)

- name: Save PM2 process list to allow resurrect on reboot
  ansible.builtin.shell: |
    set -e
    export NVM_DIR="/home/ubuntu/.nvm"
    # Source NVM
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    pm2 save
  become: true
  become_user: ubuntu
  args:
    executable: /bin/bash
  environment:
    HOME: /home/ubuntu
    PM2_HOME: /home/ubuntu/.pm2
    NVM_DIR: /home/ubuntu/.nvm
  changed_when: false