- name: "Ensure CA certificates are up-to-date"
  become: true
  apt:
    name: ca-certificates
    state: latest
    update_cache: yes

- name: "Download node exporter archive using curl."
  become: true
  shell: |
    curl -L -o /tmp/node_exporter.tar.gz {{ node_exporter_download_url }}
  args:
    creates: /tmp/node_exporter.tar.gz
  vars:
    node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"

- name: "Unarchive node exporter."
  become: true
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0755'
    owner: root
    group: root

- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    remote_src: no
    owner: root
    group: root
    mode: '0644'

- name: "enable node exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes
# ---
# - name: "Ensure CA certificates are up-to-date"
#   become: true
#   apt:
#     name: ca-certificates
#     state: latest
#     update_cache: yes

# - name: "Download node exporter archive."
#   get_url:
#     url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
#     dest: /tmp/node_exporter.tar.gz
#     mode: '0644'

# - name: "Unarchive node exporter."
#   unarchive:
#     src: /tmp/node_exporter.tar.gz
#     dest: /tmp/
#     remote_src: yes
#     creates: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter

# - name: "move binary to /usr/local/bin."
#   become: true
#   copy:
#     src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
#     dest: /usr/local/bin/node_exporter
#     remote_src: yes
#     mode: '0755'
#     owner: root
#     group: root

# - name: "add node exporter configuration."
#   become: true
#   copy:
#     src: node_exporter.service
#     dest: /etc/systemd/system/node_exporter.service
#     remote_src: no
#     owner: root
#     group: root
#     mode: '0644'

# - name: "enable node exporter service"
#   become: true
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: node_exporter
#     enabled: yes
# # ---
# - name: "Ensure CA certificates are up-to-date"  
#   become: true
#   apt:
#     name: ca-certificates
#     state: latest
#     update_cache: yes

# - name: "install node exporter."
#   unarchive:
#     src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
#     dest: /tmp
#     remote_src: yes

# - name: "move binary to /usr/local/bin."
#   become: true
#   copy:
#     src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
#     dest: /usr/local/bin/node_exporter
#     remote_src: yes
#     mode: '0777'

# - name: "add node exporter configuration."
#   become: true
#   copy:
#     src: node_exporter.service # This likely refers to a file in your Ansible files/ directory
#     dest: /etc/systemd/system/
#     # Missing remote_src: yes/no or owner/group/mode details

# - name: "enable node exporter service"
#   become: true
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: node_exporter
#     enabled: yes